# Implementation of Tic-Tac-Toe with a human against Min-Max AI agent

In [2]:
import random

def draw_board(board):
    print(board[0], "|", board[1], "|", board[2])
    print("---------")
    print(board[3], "|", board[4], "|", board[5])
    print("---------")
    print(board[6], "|", board[7], "|", board[8])

def get_player_move(board):
    valid_move = False
    while not valid_move:
        move = input("Enter your move (0-8): ")
        if move.isdigit() and int(move) >= 0 and int(move) <= 8 and board[int(move)] == " ":
            valid_move = True
        else:
            print("Invalid move, try again.")
    return int(move)

def get_ai_move(board):
    best_score = -float("inf")
    best_move = None
    for i in range(9):
        if board[i] == " ":
            board[i] = "O"
            score = min_max(board, False)
            board[i] = " "
            if score > best_score:
                best_score = score
                best_move = i
    return best_move

def min_max(board, is_maximizing):
    if check_winner(board):
        if is_maximizing:
            return -1
        else:
            return 1
    elif check_tie(board):
        return 0
    elif is_maximizing:
        best_score = -float("inf")
        for i in range(9):
            if board[i] == " ":
                board[i] = "O"
                score = min_max(board, False)
                board[i] = " "
                if score > best_score:
                    best_score = score
        return best_score
    else:
        best_score = float("inf")
        for i in range(9):
            if board[i] == " ":
                board[i] = "X"
                score = min_max(board, True)
                board[i] = " "
                if score < best_score:
                    best_score = score
        return best_score

def check_winner(board):
    for i in range(3):
        if board[i] != " " and board[i] == board[i + 3] and board[i] == board[i + 6]:
            return True
    for i in range(0, 9, 3):
        if board[i] != " " and board[i] == board[i + 1] and board[i] == board[i + 2]:
            return True
    if board[0] != " " and board[0] == board[4] and board[0] == board[8]:
        return True
    if board[2] != " " and board[2] == board[4] and board[2] == board[6]:
        return True
    return False

def check_tie(board):
    return not " " in board


def play_game():
    board = [" " for _ in range(9)]
    player_turn = random.choice([True, False])
    print("Welcome to Tic-Tac-Toe!")
    draw_board(board)
    while True:
        if player_turn:
            move = get_player_move(board)
            board[move] = "X"
        else:
            print("AI is making a move...")
            move = get_ai_move(board)
            board[move] = "O"
        draw_board(board)
        if check_winner(board):
            if player_turn:
                print("Congratulations! You win!")
            else:
                print("Sorry, the AI wins.")
            break
        elif check_tie(board):
            print("It's a tie!")
            break
        player_turn = not player_turn

if __name__ == "__main__":
    play_game()


Welcome to Tic-Tac-Toe!
  |   |  
---------
  |   |  
---------
  |   |  
Enter your move (0-8): 4
  |   |  
---------
  | X |  
---------
  |   |  
AI is making a move...
O |   |  
---------
  | X |  
---------
  |   |  
Enter your move (0-8): 3
O |   |  
---------
X | X |  
---------
  |   |  
AI is making a move...
O |   |  
---------
X | X | O
---------
  |   |  
Enter your move (0-8): 2
O |   | X
---------
X | X | O
---------
  |   |  
AI is making a move...
O |   | X
---------
X | X | O
---------
O |   |  
Enter your move (0-8): 2
Invalid move, try again.
Enter your move (0-8): 1
O | X | X
---------
X | X | O
---------
O |   |  
AI is making a move...
O | X | X
---------
X | X | O
---------
O | O |  
Enter your move (0-8): 8
O | X | X
---------
X | X | O
---------
O | O | X
It's a tie!


To play the game, simply run the code and follow the instructions in the terminal. The AI will use the Min-Max algorithm to determine its moves, and the player will be prompted to enter their moves using the keyboard.

## Implementation of a Tic-Tac-Toe game by a human against an AI agent using Alpha-Beta pruning:

In [3]:
import random

def draw_board(board):
    print(board[0], "|", board[1], "|", board[2])
    print("---------")
    print(board[3], "|", board[4], "|", board[5])
    print("---------")
    print(board[6], "|", board[7], "|", board[8])

def get_player_move(board):
    valid_move = False
    while not valid_move:
        move = input("Enter your move (0-8): ")
        if move.isdigit() and int(move) in range(9) and board[int(move)] == " ":
            return int(move)
        else:
            print("Invalid move, please try again.")

def check_winner(board):
    winning_positions = [
        (0, 1, 2), (3, 4, 5), (6, 7, 8),
        (0, 3, 6), (1, 4, 7), (2, 5, 8),
        (0, 4, 8), (2, 4, 6)
    ]
    for a, b, c in winning_positions:
        if board[a] == board[b] == board[c] != " ":
            return True
    return False

def check_tie(board):
    return " " not in board

def get_ai_move(board):
    _, move = minimax(board, True, -float("inf"), float("inf"))
    return move

def minimax(board, is_maximizing_player, alpha, beta):
    if check_winner(board):
        return (-1 if is_maximizing_player else 1, None)
    elif check_tie(board):
        return (0, None)

    if is_maximizing_player:
        best_score = -float("inf")
        for i in range(9):
            if board[i] == " ":
                board[i] = "O"
                score, _ = minimax(board, False, alpha, beta)
                board[i] = " "
                if score > best_score:
                    best_score = score
                    best_move = i
                alpha = max(alpha, best_score)
                if beta <= alpha:
                    break
        return (best_score, best_move)
    else:
        best_score = float("inf")
        for i in range(9):
            if board[i] == " ":
                board[i] = "X"
                score, _ = minimax(board, True, alpha, beta)
                board[i] = " "
                if score < best_score:
                    best_score = score
                    best_move = i
                beta = min(beta, best_score)
                if beta <= alpha:
                    break
        return (best_score, best_move)


def play_game():
    board = [" " for _ in range(9)]
    player_turn = random.choice([True, False])
    print("Welcome to Tic-Tac-Toe!")
    draw_board(board)
    while True:
        if player_turn:
            move = get_player_move(board)
            board[move] = "X"
        else:
            print("AI is making a move...")
            move = get_ai_move(board)
            board[move] = "O"
        draw_board(board)
        if check_winner(board):
            if player_turn:
                print("Congratulations! You win!")
            else:
                print("Sorry, the AI wins.")
            break
        elif check_tie(board):
            print("It's a tie!")
            break
        player_turn = not player_turn

if __name__ == "__main__":
    play_game()


Welcome to Tic-Tac-Toe!
  |   |  
---------
  |   |  
---------
  |   |  
Enter your move (0-8): 0
X |   |  
---------
  |   |  
---------
  |   |  
AI is making a move...
X |   |  
---------
  | O |  
---------
  |   |  
Enter your move (0-8): 1
X | X |  
---------
  | O |  
---------
  |   |  
AI is making a move...
X | X | O
---------
  | O |  
---------
  |   |  
Enter your move (0-8): 6
X | X | O
---------
  | O |  
---------
X |   |  
AI is making a move...
X | X | O
---------
O | O |  
---------
X |   |  
Enter your move (0-8): 5
X | X | O
---------
O | O | X
---------
X |   |  
AI is making a move...
X | X | O
---------
O | O | X
---------
X | O |  
Enter your move (0-8): 8
X | X | O
---------
O | O | X
---------
X | O | X
It's a tie!


## Implementation of a Tic-Tac-Toe with a human against an AI agent using Q-learning:

In [10]:
import numpy as np
import random

# Initialize Q-values
Q = {}

# Hyperparameters
alpha = 0.1 # learning rate
gamma = 0.9 # discount factor
epsilon = 0.1 # exploration probability

# Define game state and action space
state_space = [[0, 0, 0] for i in range(3)]
action_space = [(i, j) for i in range(3) for j in range(3)]

# Define reward function
def reward(state):
    if any(sum(row) == 3 for row in state): # check rows
        return 1
    if any(sum(col) == 3 for col in zip(*state)): # check columns
        return 1
    if sum(state[i][i] for i in range(3)) == 3: # check diagonal
        return 1
    if sum(state[i][2-i] for i in range(3)) == 3: # check diagonal
        return 1
    if any(sum(row) == -3 for row in state): # check rows
        return -1
    if any(sum(col) == -3 for col in zip(*state)): # check columns
        return -1
    if sum(state[i][i] for i in range(3)) == -3: # check diagonal
        return -1
    if sum(state[i][2-i] for i in range(3)) == -3: # check diagonal
        return -1
    return 0

# Define epsilon-greedy policy
def epsilon_greedy_policy(state, epsilon):
    if random.uniform(0, 1) < epsilon:
        return random.choice(action_space)
    else:
        #q_values = [Q.get((tuple(state), action), 0) for action in action_space]
        q_values = [Q.get((tuple(map(tuple, state)), action), 0) for action in action_space]
        max_q_value = max(q_values)
        count = q_values.count(max_q_value)
        if count > 1:
            best_actions = [action_space[i] for i in range(len(action_space)) if q_values[i] == max_q_value]
            return random.choice(best_actions)
        else:
            return action_space[q_values.index(max_q_value)]

# Define Q-learning algorithm
#def q_learning(state, action, next_state, reward, alpha, gamma):
#   max_next_q_value = max([Q.get((tuple(next_state), next_action), 0) for next_action in action_space])
#   current_q_value = Q.get((tuple(state), action), 0)
#    Q[(tuple(state), action)] = current_q_value + alpha * (reward + gamma * max_next_q_value - current_q_value)
    
def q_learning(state, action, next_state, reward, alpha, gamma):
    state = tuple(map(tuple, state))
    next_state = tuple(map(tuple, next_state))
    # Get Q-value for current state-action pair
    q_value = Q.get((state, action), 0)
    # Compute the maximum Q-value for the next state
    #max_q_value = max([Q.get((next_state, a), 0) for a in action_space(next_state)])
    max_q_value = max([Q.get((next_state, a), 0) for a in action_space])
    # Update Q-value using Q-learning formula
    #Q[(state, action)] = q_value + alpha * (reward + gamma * max_q_value - q_value)
    Q[tuple(map(tuple, state)), action] = q_value + alpha * (reward + gamma * max_q_value - q_value)


# Initialize game
state = state_space.copy()
while True:
    # Human player's turn
    print("Current state:")
    print(np.array(state))
    #row, col = input("Enter row and column (0-2): ").split()
    input_str = input("Enter row and column (0-2): ")
    row, col = input_str.split('-') if '-' in input_str else input_str.split()
    row, col = int(row), int(col)
    if state[row][col] != 0:
        print("Invalid move, try again.")
        continue
    state[row][col] = 1
    reward_value = reward(state)
    if reward_value != 0:
        print("You won!")
        break
    if all(all(row) for row in state):
        print("Tie!")
        break
    # AI agent's turn
    action = epsilon_greedy_policy(state, epsilon)
    state[action[0]][action[1]] = -1
    reward_value = reward(state)
    
    if reward_value != 0:
        print("You lost!")
        break
    if all(all(row) for row in state):
        print("Tie!")
        break

# Update Q-values
q_learning(state, action, state, reward_value, alpha, gamma)


Current state:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Enter row and column (0-2): 0-1
Current state:
[[-1  1  0]
 [ 0  0  0]
 [ 0  0  0]]
Enter row and column (0-2): 1-1
Current state:
[[-1  1  0]
 [-1  1  0]
 [ 0  0  0]]
Enter row and column (0-2): 1-2
Current state:
[[-1  1  0]
 [-1  1  1]
 [ 0  0  0]]
Enter row and column (0-2): 2-1
You won!


## Implementing TIC-TAC-TOE using all AI Agents (MIN_MAX, ALPHA_BETA, Q-LEARNING)

In [17]:
from random import choice
from math import inf

board = [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]

def Gameboard(board):
    chars = {1: 'X', -1: 'O', 0: ' '}
    for x in board:
        for y in x:
            ch = chars[y]
            print(f'| {ch} |', end='')
        print('\n' + '---------------')
    print('===============')

def Clearboard(board):
    for x, row in enumerate(board):
        for y, col in enumerate(row):
            board[x][y] = 0

def winningPlayer(board, player):
    conditions = [[board[0][0], board[0][1], board[0][2]],
                     [board[1][0], board[1][1], board[1][2]],
                     [board[2][0], board[2][1], board[2][2]],
                     [board[0][0], board[1][0], board[2][0]],
                     [board[0][1], board[1][1], board[2][1]],
                     [board[0][2], board[1][2], board[2][2]],
                     [board[0][0], board[1][1], board[2][2]],
                     [board[0][2], board[1][1], board[2][0]]]

    if [player, player, player] in conditions:
        return True

    return False

def gameWon(board):
    return winningPlayer(board, 1) or winningPlayer(board, -1)

def printResult(board):
    if winningPlayer(board, 1):
        print('X has won!, Min Max  ' + '\n')

    elif winningPlayer(board, -1):
        print('O\'s have won!, Alpha Beta Pruning  ' + '\n')

    else:
        print('Draw' + '\n')

def blanks(board):
    blank = []
    for x, row in enumerate(board):
        for y, col in enumerate(row):
            if board[x][y] == 0:
                blank.append([x, y])

    return blank

def boardFull(board):
    if len(blanks(board)) == 0:
        return True
    return False

def setMove(board, x, y, player):
    board[x][y] = player

def playerMove(board):
    e = True
    moves = {1: [0, 0], 2: [0, 1], 3: [0, 2],
             4: [1, 0], 5: [1, 1], 6: [1, 2],
             7: [2, 0], 8: [2, 1], 9: [2, 2]}
    while e:
        try:
            move = int(input('Enter a number between 1-9: '))
            if move < 1 or move > 9:
                print('Invalid Move! Try again!')
            elif not (moves[move] in blanks(board)):
                print('Invalid Move! Try again!')
            else:
                setMove(board, moves[move][0], moves[move][1], 1)
                Gameboard(board)
                e = False
        except(KeyError, ValueError):
            print('Enter a number!')

def getScore(board):
    if winningPlayer(board, 1):
        return 10

    elif winningPlayer(board, -1):
        return -10

    else:
        return 0

    
class QLearningPlayer():
    def __init__(self):
        self.name = 'Q-Learning'
        self.q = {}
        self.init_q = 1 # "optimistic" 1.0 initial values
        self.lr = 0.3
        self.gamma = 0.9
        self.epsilon = 1.0
        self.max_epsilon = 1.0
        self.min_epsilon = 0.01
        self.decay_rate = 0.01
        self.action_n = 9
        self.win_n = 0

        self.last_state = (' ',) * 9
        self.last_action = -1

    def action(self, state, actions):
        state = tuple(state)
        self.last_state = state

        r = random.uniform(0, 1)
        if r > self.epsilon:
            if self.q.get(state):
                i = np.argmax([self.q[state][a] for a in actions])
                action = actions[i]
            else:
                self.q[state] = [self.init_q] * self.action_n
                action = random.choice(actions)
        else:
            action = random.choice(actions)

        self.last_action = action
        return action

    def reward(self, reward, state):
        if self.last_action >= 0:
            if reward == 1:
                self.win_n += 1

            state = tuple(state)
            if self.q.get(self.last_state):
                q = self.q[self.last_state][self.last_action]
            else:
                self.q[self.last_state] = [self.init_q] * self.action_n
                q = self.init_q

            self.q[self.last_state][self.last_action] = q + self.lr * (reward + self.gamma * np.max(self.q.get(state, [self.init_q]*self.action_n)) - q)

    def episode_end(self, episode):
        # epsilon decay
        self.epsilon = self.min_epsilon + (self.max_epsilon - self.min_epsilon) * np.exp(-self.decay_rate*(episode+1))

    def print_q(self):
        for k,v in self.q.items():
            print(k,v)
    
def minimax(state, depth, player):
    """
    AI function that choice the best move
    :param state: current state of the board
    :param depth: node index in the tree (0 <= depth <= 9),
    but never nine in this case (see iaturn() function)
    :param player: an human or a computer
    :return: a list with [the best row, best col, best score]
    """
    if player == -1:
        best = [-1, -1, -10000000]
    else:
        best = [-1, -1, +10000000]

    if depth == 0 or gameWon(state):
        score = getScore(state)
        return [-1, -1, score]

    for cell in blanks(state):
        x, y = cell[0], cell[1]
        state[x][y] = player
        score = minimax(state, depth - 1, -player)
        state[x][y] = 0
        score[0], score[1] = x, y

        if player == -1:
            if score[2] > best[2]:
                best = score  # max value
        else:
            if score[2] < best[2]:
                best = score  # min value

    return best

def abminimax(board, depth, alpha, beta, player):
    row = -1
    col = -1
    if depth == 0 or gameWon(board):
        return [row, col, getScore(board)]

    else:
        for cell in blanks(board):
            setMove(board, cell[0], cell[1], player)
            score = abminimax(board, depth - 1, alpha, beta, -player)
            if player == 1:
                # X is always the max player
                if score[2] > alpha:
                    alpha = score[2]
                    row = cell[0]
                    col = cell[1]

            else:
                if score[2] < beta:
                    beta = score[2]
                    row = cell[0]
                    col = cell[1]

            setMove(board, cell[0], cell[1], 0)

            if alpha >= beta:
                break

        if player == 1:
            return [row, col, alpha]

        else:
            return [row, col, beta]

def o_comp(board):
    if len(blanks(board)) == 9:
        #x = choice([0, 1, 2])
        #y = choice([0, 1, 2])
        move = minimax(board, len(blanks(board)), +1)
        x, y = move[0], move[1]
        setMove(board, x, y, -1)
        Gameboard(board)

    else:
        result = abminimax(board, len(blanks(board)), -inf, inf, -1)
        setMove(board, result[0], result[1], -1)
        Gameboard(board)

def x_comp(board):
    if len(blanks(board)) == 9:
        #x = choice([0, 1, 2])
        #y = choice([0, 1, 2])
        move = minimax(board, len(blanks(board)), +1)
        x, y = move[0], move[1]
        setMove(board, x, y, 1)
        Gameboard(board)

    else:
        result = abminimax(board, len(blanks(board)), -inf, inf, 1)
        setMove(board, result[0], result[1], 1)
        Gameboard(board)

def makeMove(board, player, mode):
    if mode == 1:
        if player == 1:
            minimax(board,len(blanks(board)),player)

        else:
            o_comp(board)
    else:
        if player == 1:
            o_comp(board)
        else:
            x_comp(board)

def pvc():
    currentPlayer = 1
    """while True:
        try:
            order = int(input('Enter to play 1st or 2nd: '))
            if not (order == 1 or order == 2):
                print('Please pick 1 or 2')
            else:
                break
        except(KeyError, ValueError):
            print('Enter a number')

    Clearboard(board)
    if order == 2:
        currentPlayer = -1
    else:
        currentPlayer = 1"""

    while not (boardFull(board) or gameWon(board)):
        makeMove(board, currentPlayer, 1)
        currentPlayer *= -1
        makeMove(board, currentPlayer, -1)
        currentPlayer *= 1

    printResult(board)

# Driver Code
print("=================================================")
print("TIC-TAC-TOE using MINIMAX with MIN MAX OVER ALPHA-BETA Pruning")
print("=================================================")
pvc()  


TIC-TAC-TOE using MINIMAX with MIN MAX OVER ALPHA-BETA Pruning
|   ||   ||   |
---------------
|   || X ||   |
---------------
|   ||   ||   |
---------------
| O ||   ||   |
---------------
|   || X ||   |
---------------
|   ||   ||   |
---------------
| O || O ||   |
---------------
|   || X ||   |
---------------
|   ||   ||   |
---------------
| O || O || X |
---------------
|   || X ||   |
---------------
|   ||   ||   |
---------------
| O || O || X |
---------------
|   || X ||   |
---------------
| O ||   ||   |
---------------
| O || O || X |
---------------
| O || X ||   |
---------------
| O ||   ||   |
---------------
O's have won!, Alpha Beta Pruning  

